_wandb:
    value:
        cli_version: 0.25.0
        code_path: code/main.py
        e:
            615mvb2o4wgiki7l39ukn9gwns8w4we9:
                codePath: main.py
                codePathLocal: main.py
                email: barryyeh0916@gmail.com
                executable: /home/barryyeh0916/repos/ducks-riding-lamas/.pixi/envs/default/bin/python
                git:
                    commit: 6bf8768c9bccf5c4e665f97f46b360533b40fb8d
                    remote: git@github.com:fivecodingfive/ducks-riding-lamas.git
                host: barryyeh0916-ThinkPad-P16-Gen-1
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: /home/barryyeh0916/repos/ducks-riding-lamas/main.py
                python: CPython 3.11.14
                root: ./wandb
                startedAt: "2026-02-21T17:29:23.516850Z"
                writerId: 615mvb2o4wgiki7l39ukn9gwns8w4we9
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 2
                - 3
            "2":
                - 2
                - 3
            "3":
                - 13
                - 15
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
environment:
    value:
        mode: training
        variant: 0
model:
    value:
        device: cpu
        network: mlp
training:
    value:
        episodes: 100
        gamma: 0.99
        learning_rate: 0.001
        seed: 42
